spring.application.name=Trackery-FrontServer
logging.level.org.springframework.security=DEBUG
server.port=${SERVER_PORT}
api.server.url=${BASE_PATH}
spring.mvc.contentnegotiation.media-types.webp=image/webp
# OAuth ?? URL ??
oauth.google.auth-url=${GOOGLE_OAUTH}
oauth.kakao.auth-url=${KAKAO_OAUTH}
oauth.naver.auth-url=${NAVER_OAUTH}
oauth.github.auth-url=${GITHUB_OAUTH}
kostat.consumerKey=${KOSTAT_CONSUMER_KEY}
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/